### ISSUE TITLE
One case fails to remove invisible texts or symbols

### ISSUE THREAD

**Issue by zhongguogu** [mkl-public/testarea-pdfbox2#3]
Hi,There is one case that fails  to remove  invisible text by  PDFVisibleTextStripper.java.
In PDF page One.
 

[00000000000005fw6q.pdf](https://github.com/mkl-public/testarea-pdfbox2/files/2481423/00000000000005fw6q.pdf)
![invisible](https://user-images.githubusercontent.com/39140455/46993053-cd299780-d13f-11e8-8c51-0767c1db1bac.png)

**Comment by mkl-public** [comment]
Please consider all classes in this repository in their respective context. The context usually is apparent from its JavaDoc. For `PDFVisibleTextStripper` this says

```
/**
 * <a href="https://stackoverflow.com/questions/47358127/remove-invisible-text-from-pdf-using-pdfbox">
 * remove invisible text from pdf using pdfbox
 * </a>
 * <br/>
 * <a href="https://drive.google.com/file/d/1F8vrzcABwxVGdN5W-7etQggY5xKtGplU/view">
 * RevTeaser09072016.pdf
 * </a>
 * <p>
 * This class extends the {@link PDFTextStripper} to ignore text hidden by
 * clipping or by covering with a filled path.
 * </p>
 * <p>
 * The {@link PDFTextStripper} does not implement call backs for path related
 * instructions but the {@link PageDrawer} does. So we borrow code from there
 * to implement path related behavior here.
 * </p>
 * 
 * @author mkl
 */
```

So this class only _ignores text hidden by clipping or by covering with a filled path_, not other hidden text. For an extractor that recognizes all kinds of invisible text as ignorable there is much more to implement, cf. the answers to many similar questions on SO, in particular those by [Dmitry K](https://stackoverflow.com/users/9123040/dmitry-k).

The "hidden text" in question, though, is neither hidden by a clip path nor covered by some filled path, it simply is a glyph visually without any content. On the other hand there is a *ToUnicode* entry for it mapping it to U+DBD0 during text extraction, a High Private Use Surrogate which by itself in general makes no sense; after text extraction it therefore usually will show up as a '�', i.e. a replacement character.

Adobe most likely considers this "hidden text" because it is an empty glyph with a *ToUnicode* mapping to a codepoint outside the 'Separator, Space' category.
